select 
    mon12.month_,
    sum( mon12.v_lo ) sum_of_v_lo,
    sum( mon12.v_co ) sum_of_v_co,
    sum( mon12.bonus ) sum_of_bonus,
    sum( mon12.co_mp1 ) sum_of_co_mp1,
    sum( mon12.bonus_lo_mp1 ) sum_of_bonus_lo_mp1,
    sum( mon12.bonus_90_180_mp1 ) sum_of_bonus_90_180_mp1,
    sum( mon12.bonus_180_mp1 ) sum_of_bonus_180_mp1,
    sum( mon12.bonus_minus_mp1 ) sum_of_bonus_minus_mp1,
    sum( mon12.bonus_new_distr_avtor_mp1 ) sum_of_bonus_new_distr_avtor_mp1,
    sum( mon12.bonus_pp_mp1 ) sum_of_bonus_pp_mp1,
    sum( mon12.lo_mp1 ) sum_of_lo_mp1,
    sum( mon12.legs_sum_mp1 ) sum_of_legs_sum_mp1,
    sum( mon12.legs_procent ) sum_of_legs_procent,
    sum( mon12.lo_mp2 ) sum_of_lo_mp2,
    sum( mon12.v_for_kesh ) sum_of_v_for_kesh,
    sum( mon12.bonus_15 ) sum_of_bonus_15,
    sum( mon12.bonus_30 ) sum_of_bonus_30,
    sum( mon12.v_lo_kesh ) sum_of_v_lo_kesh,
    sum( mon12.bonus_pp_kesh ) sum_of_bonus_pp_kesh,
    sum( mon12.procent_bonus_kesh ) sum_of_procent_bonus_kesh,
    sum( mon12.co_mp2 ) sum_of_co_mp2,
    sum( mon12.bonus_kesh_lpp_mp2 ) sum_of_bonus_kesh_lpp_mp2,
    sum( mon12.bonus_90_mp2 ) sum_of_bonus_90_mp2,
    sum( mon12.bonus_mentor ) sum_of_bonus_mentor,
    sum( mon12.bonus__pp_mp2 ) sum_of_bonus__pp_mp2,
    sum( mon12.bonus_avtor_mp2 ) sum_of_bonus_avtor_mp2,
    sum( mon12.bonus_lb_mp2 ) sum_of_bonus_lb_mp2,
    sum( mon12.bonus_lb_mp2_what ) sum_of_bonus_lb_mp2_what
from mon12
group by mon12.month_
